apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  containers:
  - name: nc
    args:
    - apache2-foreground
    image: docker.io/library/nextcloud:stable
    envFrom:
      - configMapRef:
          name: nextcloud
    env:
    - name: OVERWRITEPROTOCOL
      value: "https"
    - name: MYSQL_HOST
      value: 127.0.0.1:3306
    - name: REDIS_HOST
      value: 127.0.0.1
    - name: NEXTCLOUD_UPDATE
      value: 1
    - name: PHP_UPLOAD_LIMIT
      value: "10G"
    ports:
    - containerPort: 80
      hostPort: 8010
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - name: config
      mountPath: /var/www/html/config
    - name: data
      mountPath: /var/www/html/data
    - name: themes
      mountPath: /var/www/html/themes

  - name: db
    image: docker.io/library/mariadb:10.5
    args:
    - mariadbd
    - --transaction-isolation=READ-COMMITTED
    - --log-bin=binlog
    - --binlog-format=ROW
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    envFrom:
      - configMapRef:
          name: db
    volumeMounts:
    - name: db
      mountPath: /var/lib/mysql

  - name: redis
    image: docker.io/library/redis:latest
    args:
    - redis-server
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - name: redis
      mountPath: /data

  volumes:
  - name: config
    hostPath:
      path: /media/nextcloud/config
      type: Directory
  - name: data
    hostPath:
      path: /media/nextcloud/data
      type: Directory
  - name: themes
    hostPath:
      path: /media/nextcloud/themes
      type: Directory
  - name: db
    hostPath:
      path: /media/nextcloud/db
      type: Directory
  - name: redis
    persistentVolumeClaim:
          claimName: nextcloud-redis
