apiVersion: v1
kind: ConfigMap
metadata:
    name: nextcloud
data:
    OVERWRITEHOST: ENC[AES256_GCM,data:/gew8QTtMTezu5AhtQ==,iv:KO/e9gOROajwZa93BfUg5cPqc5sgsmhobP5fWN6IDBI=,tag:KzkAy8i8wUyXas4ksDieRA==,type:str]
    OVERWRITECLIURL: ENC[AES256_GCM,data:JWp5JMaGQx+4fVw3xtSSa6pORzxE,iv:6DWOlT5QkLfl4pGUQEcsfOIggPBlcdaBbTagTfQPDdE=,tag:pxC5YRb1Ok1TT9joQYe+OQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:TFi12tql1CQs,iv:8vSUVwINqAC5g4a7ovl+Ga0eOJCrx3ZyV/3oORLyOU8=,tag:y5etaWO2DZGTezwoVKwq2A==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:02dGUg==,iv:pxVThbUcbcBvRRlZEW3ZNJQlP+GESI/dg6a4zyJGmzA=,tag:eMlfFD6S0hAU+VHI8zFU/Q==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:t99ImdRB1GTTwZBL8iM+5J+n3tx0Xxr7+H1XMag=,iv:6YwauI4tJipP7JHLHRx8DlhEIYa0OCefdm5ZOFjo7Mo=,tag:jhj8ZBgAU0K3TTkTSGt6Og==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:JKRXWYc=,iv:GqrbKeb3KjERnabVRYmWm6gpjRO7py3hmZCZjmUv07Y=,tag:BruAwk4c7B7DkJBgnyiCtg==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:uSPDvTEsMMwlGvHvnKc9nSYLXwzYBndFFCQaoI/Xyxg=,iv:aFIwwlM34NOvppI0bk35V5UKRnrOZ7+Ryoj+XupfKW8=,tag:a68k3UyVceTUay/WjfbgLQ==,type:str]
    NEXTCLOUD_TRUSTED_DOMAINS: ENC[AES256_GCM,data:qEpzh27tK/iphM/UTcekL1X5QPwf9hv78RvB1eDsIWojqF66cNucsF7m9A8oPTw=,iv:6llMt6g1IlTT5aW6qcTyO9k5vDDmhxa++QdB1K35EnI=,tag:BFyCpDCYtkvTZTLlkLMvpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z2232lgdxu2lj20sk6ca7uzcpg7mmecza36e72qa6dqa2vkxwykq7d45za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQk9DYVJzVkNhYTZnSXFM
            WGhZZktUYlVDbS9zUEREY1VWV1pDYVViRnpRCnh1WFkwMVZoU0l1WTdxOTZxRFBE
            Zm1TWU1vNSt2M0lsYjZLNitRcmpFa3cKLS0tIDAxRXVSZVFSRkFlS3J0aldVVUI5
            NzBIYnpJdEdPdFpFUWRQekxWS2xQcm8KZ7xD+Pudm6pZuPVJaOSNI2H7ozAXN/Uk
            dcif6yn52qC9h4aMULz6fOp9Hf1you908CO+SxcC0Qs2yVO1V4I3Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T17:39:49Z"
    mac: ENC[AES256_GCM,data:LHorgfOkUPIa+u1b9wrowy1RdptXt2wFqZuYlxrM1KvtjRvAna4XPlejWL7PrXbnTalTGUW7W14WHF50xbXigcHGejd4ng7b9uZ3GvIYO+noRNM1Hn4Ao62bAnPTkO6lVLXBYdDj/kvfAd+majZBoNAett1ZqZUsSzTVP4nd87o=,iv:Km0XTngLHlbDi+JdT6Mk63E5wOJOHQXX/V4ElNm9fWc=,tag:mgJIKTEsgvB/dW2GePI+fA==,type:str]
    pgp: []
    encrypted_regex: ^data
    version: 3.7.3
